# Generated by Django 5.1.7 on 2026-06-09 03:12

import django.db.models.deletion
import media_hub.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=media_hub.models.media_upload_path, verbose_name='File ảnh')),
                ('original_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Kích thước file (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
            },
        ),
    ]
